name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Run tests
        run: go test -v ./...
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Static analysis
        uses: golangci/golangci-lint-action@v2
